"""CM-217 add user's ip_address to Sessions table, column: ip_address

Revision ID: 0ad601cccfdd
Revises: 04f4c14bd4af
Create Date: 2020-12-27 08:46:17.016221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0ad601cccfdd"
down_revision = "04f4c14bd4af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions", sa.Column("ip_address", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "ip_address")
    # ### end Alembic commands ###
