"""CM-791 add postal code column to scores and timestamp to sessions

Revision ID: ff1d6f5eb900
Revises: 8c375095efa7
Create Date: 2021-08-29 15:50:34.971577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ff1d6f5eb900"
down_revision = "8c375095efa7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scores", sa.Column("postal_code", sa.String(length=5), nullable=True)
    )
    op.add_column(
        "sessions", sa.Column("session_created_timestamp", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "session_created_timestamp")
    op.drop_column("scores", "postal_code")
    # ### end Alembic commands ###
