version: "3"
services:
  web:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile.m1
    ports:
      - "8050:8050"
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      DATABASE_PARAMS: Driver={ODBC Driver 17 for SQL Server};Server=tcp:db,1433;Database=sqldb-web-prod-001;Uid=sa;Pwd=Cl1mat3m1nd!;Encrypt=no;TrustServerCertificate=no;Connection Timeout=30;
      #DATABASE_PARAMS: ${CLOUD_DB_PARAMS}
      #DATABASE_PARAMS: ${TEST_DB_PARAMS}
      RECAPTCHA_SECRET_KEY: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
      FLASK_APP: "climatemind.py"
    command: ["./wait-for-it", "db:1433"]
    stdin_open: true
    tty: true
    links:
      - "db"
    depends_on:
      - "db"
  db:
    build:
      context: ./
      dockerfile: Dockerfile.db
    ports:
        - "1433:1433"
    environment:
      DATABASE_PARAMS: Driver={ODBC Driver 17 for SQL Server};Server=tcp:db,1433;Database=tempdb;Uid=SA;Pwd=Cl1mat3m1nd!;Encrypt=no;TrustServerCertificate=no;Connection Timeout=30;
      MSSQL_SA_PASSWORD: "Cl1mat3m1nd!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./entrypoint.db.sh:/entrypoint.db.sh
      - ./db-init.py:/db-init.py
      - ./db-init.m1.sh:/db-init.m1.sh
