"""CM-791 add fk constraints for session_uuid in climatefeed and signup

Revision ID: df2fd4177138
Revises: 450507f4071f
Create Date: 2021-08-29 17:40:07.037225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "df2fd4177138"
down_revision = "450507f4071f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "climate_feed", "sessions", ["session_uuid"], ["session_uuid"]
    )
    op.create_foreign_key(
        None, "signup", "sessions", ["session_uuid"], ["session_uuid"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "signup", type_="foreignkey")
    op.drop_constraint(None, "climate_feed", type_="foreignkey")
    # ### end Alembic commands ###
