version: "3"
services:
  api:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: ./docker/services/api/m1/Dockerfile.m1
    ports:
      - "8050:8050"
      - "5000:5000"
    volumes:
      - ..:/app
    environment:
      IS_LOCAL: "True"
      DATABASE_PARAMS: Driver={ODBC Driver 17 for SQL Server};Server=tcp:db,1433;Database=sqldb-web-prod-001;Uid=sa;Pwd=Cl1mat3m1nd!;Encrypt=no;TrustServerCertificate=no;Connection Timeout=30;
      TEST_DATABASE_PARAMS: Driver={ODBC Driver 17 for SQL Server};Server=tcp:db,1433;Uid=sa;Pwd=Cl1mat3m1nd!;Encrypt=no;TrustServerCertificate=no;Connection Timeout=30;
      RECAPTCHA_SECRET_KEY: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
      FLASK_APP: "climatemind.py"
    command: ["./wait-for-it", "db:1433"]
    stdin_open: true
    tty: true
    links:
      - "db"
    depends_on:
      - "db"
  db:
    build:
      context: ..
      dockerfile: ./docker/services/db/m1/Dockerfile.db
    ports:
        - "1433:1433"
    environment:
      DATABASE_PARAMS: Driver={ODBC Driver 17 for SQL Server};Server=tcp:db,1433;Database=tempdb;Uid=SA;Pwd=Cl1mat3m1nd!;Encrypt=no;TrustServerCertificate=no;Connection Timeout=30;
      MSSQL_SA_PASSWORD: "Cl1mat3m1nd!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql
  webapp:
    image: climatemind/webapp:develop-m1
    depends_on:
      - db
      - api
    ports:
      - "3000:3000"
    profiles:
      - webapp

volumes:
  mssql_data:
    driver: local
