"""add all current tables

Revision ID: 0f9037f611da
Revises: dacf52387926
Create Date: 2021-10-11 01:03:01.420786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "0f9037f611da"
down_revision = "dacf52387926"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_lrf_data_postal_code", table_name="lrf_data")
    op.drop_table("lrf_data")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lrf_data",
        sa.Column("postal_code", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "http://webprotege.stanford.edu/R9vkBr0EApzeMGfa0rJGo9G",
            mssql.BIT(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "http://webprotege.stanford.edu/RJAL6Zu9F3EHB35HCs3cYD",
            mssql.BIT(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "http://webprotege.stanford.edu/RcIHdxpjQwjr8EG8yMhEYV",
            mssql.BIT(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "http://webprotege.stanford.edu/RDudF9SBo28CKqKpRN9poYL",
            mssql.BIT(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "http://webprotege.stanford.edu/RLc1ySxaRs4HWkW4m5w2Me",
            mssql.BIT(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        "ix_lrf_data_postal_code", "lrf_data", ["postal_code"], unique=False
    )
    # ### end Alembic commands ###
