FROM mcr.microsoft.com/azure-sql-edge:1.0.5
USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.8 \
    python3-pip \
    python3-dev \
    gcc \
    g++ \
    unixodbc \
    unixodbc-dev \
    && apt-get clean

RUN pip3 install --upgrade setuptools \
    && pip3 install ez_setup pyodbc sqlalchemy

WORKDIR /app/
COPY ./docker/services/db/m1/entrypoint.db.sh ./entrypoint.db.sh
COPY ./docker/services/db/m1/db-init.py ./db-init.py
COPY ./docker/services/db/m1/db-init.m1.sh ./db-init.m1.sh

USER mssql
ENTRYPOINT ["/bin/bash", "./entrypoint.db.sh"]