"""CM-246 edit postal_code column in sessions table - change data type to string - edited env.py to detect column type changes

Revision ID: 153174730e99
Revises: 0ee385c8519b
Create Date: 2020-12-29 09:28:11.401801

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "153174730e99"
down_revision = "0ee385c8519b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sessions",
        "postal_code",
        existing_type=sa.INTEGER(),
        type_=sa.String(length=5),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sessions",
        "postal_code",
        existing_type=sa.String(length=5),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
