"""CM-563 Add full_name to users

Revision ID: f67f1970ee20
Revises: 2163c84d2cc6
Create Date: 2021-05-03 22:20:30.103778

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "f67f1970ee20"
down_revision = "2163c84d2cc6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("full_name", sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###
