"""CM-791 change full name to first and last name

Revision ID: 866bfbbdeee0
Revises: 86dbb3c839d6
Create Date: 2021-08-29 16:58:50.029641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "866bfbbdeee0"
down_revision = "86dbb3c839d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions", sa.Column("user_uuid", mssql.UNIQUEIDENTIFIER(), nullable=True)
    )
    op.create_foreign_key(None, "sessions", "users", ["user_uuid"], ["user_uuid"])
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=50), nullable=False)
    )
    op.add_column("users", sa.Column("last_name", sa.String(length=50), nullable=False))
    op.create_index(None, "users", ["user_email"], unique=True)
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "full_name",
            sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index("ix_users__user_email", table_name="users")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_constraint("fk_sessions__user_uuid__users", "sessions", type_="foreignkey")
    op.drop_column("sessions", "user_uuid")
    # ### end Alembic commands ###
