"""CM-791 session id updates

Revision ID: 8c375095efa7
Revises: f67f1970ee20
Create Date: 2021-08-29 15:31:52.957107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8c375095efa7"
down_revision = "1a9369559ca2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_climate_feed__session_uuid__sessions", "climate_feed", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_scores__session_uuid__sessions", "scores", type_="foreignkey"
    )
    op.drop_constraint("fk_scores__user_uuid__users", "scores", type_="foreignkey")
    op.drop_constraint(
        "fk_signup__session_uuid__sessions", "signup", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_signup__session_uuid__sessions",
        "signup",
        "sessions",
        ["session_uuid"],
        ["session_uuid"],
    )
    op.create_foreign_key(
        "fk_scores__user_uuid__users", "scores", "users", ["user_uuid"], ["uuid"]
    )
    op.create_foreign_key(
        "fk_scores__session_uuid__sessions",
        "scores",
        "sessions",
        ["session_uuid"],
        ["session_uuid"],
    )
    op.create_foreign_key(
        "fk_climate_feed__session_uuid__sessions",
        "climate_feed",
        "sessions",
        ["session_uuid"],
        ["session_uuid"],
    )
    # ### end Alembic commands ###
