"""CM-749 add page_url column to analytics table

Revision ID: 1a9369559ca2
Revises: 1382a124cd8e
Create Date: 2021-06-19 16:03:07.888211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1a9369559ca2"
down_revision = "f67f1970ee20"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analytics_data", sa.Column("page_url", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analytics_data", "page_url")
    # ### end Alembic commands ###
