"""add uuid columns, drop foreign constraints

Revision ID: c643d0b48ade
Revises: 713ba83ef1ed
Create Date: 2021-02-28 19:08:48.151148

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "c643d0b48ade"
down_revision = "713ba83ef1ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "climate_feed", sa.Column("event_timestamp", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "climate_feed",
        sa.Column("session_uuid", mssql.UNIQUEIDENTIFIER(), nullable=True),
    )
    op.drop_constraint(
        "fk_climate_feed__session_id__sessions", "climate_feed", type_="foreignkey"
    )
    op.drop_column("climate_feed", "event_ts")
    op.add_column(
        "scores", sa.Column("scores_created_timestamp", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "scores", sa.Column("session_uuid", mssql.UNIQUEIDENTIFIER(), nullable=True)
    )
    op.drop_constraint("fk_scores__user_id__users", "scores", type_="foreignkey")
    op.drop_constraint("fk_scores__session_id__sessions", "scores", type_="foreignkey")
    op.add_column(
        "sessions", sa.Column("session_uuid", mssql.UNIQUEIDENTIFIER(), nullable=True)
    )
    op.add_column(
        "signup", sa.Column("session_uuid", mssql.UNIQUEIDENTIFIER(), nullable=True)
    )
    op.add_column(
        "signup",
        sa.Column("signup_id", sa.Integer(), autoincrement=True, nullable=True),
    )
    # THERE'S NO THIS FK
    # op.drop_constraint("FK__signup__session___01142BA1", "signup", type_="foreignkey")
    op.add_column(
        "users", sa.Column("user_created_timestamp", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "users", sa.Column("user_uuid", mssql.UNIQUEIDENTIFIER(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "user_uuid")
    op.drop_column("users", "user_created_timestamp")
    op.create_foreign_key(
        None,
        "signup",
        "sessions",
        ["session_id"],
        ["session_id"],
    )
    op.drop_column("signup", "signup_id")
    op.drop_column("signup", "session_uuid")
    op.drop_column("sessions", "session_uuid")
    op.create_foreign_key(
        None,
        "scores",
        "sessions",
        ["session_id"],
        ["session_id"],
    )
    op.create_foreign_key(None, "scores", "users", ["user_id"], ["user_id"])
    op.drop_column("scores", "session_uuid")
    op.drop_column("scores", "scores_created_timestamp")
    op.add_column(
        "climate_feed",
        sa.Column("event_ts", sa.DATETIME(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        None,
        "climate_feed",
        "sessions",
        ["session_id"],
        ["session_id"],
    )
    op.drop_column("climate_feed", "session_uuid")
    op.drop_column("climate_feed", "event_timestamp")
    # ### end Alembic commands ###
