"""CM-791 adjusting uuids in scores

Revision ID: 450507f4071f
Revises: c83ff90dbcbf
Create Date: 2021-08-29 17:21:58.166402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "450507f4071f"
down_revision = "c83ff90dbcbf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scores", sa.Column("session_uuid", mssql.UNIQUEIDENTIFIER(), nullable=True)
    )
    op.create_foreign_key(
        None, "scores", "sessions", ["session_uuid"], ["session_uuid"]
    )
    op.drop_column("scores", "user_uuid")
    op.add_column(
        "users", sa.Column("quiz_uuid", mssql.UNIQUEIDENTIFIER(), nullable=True)
    )
    op.create_foreign_key(None, "users", "scores", ["quiz_uuid"], ["quiz_uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users__quiz_uuid__scores", "users", type_="foreignkey")
    op.drop_column("users", "quiz_uuid")
    op.add_column(
        "scores",
        sa.Column(
            "user_uuid", mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(
        "fk_scores__session_uuid__sessions", "scores", type_="foreignkey"
    )
    op.drop_column("scores", "session_uuid")
    # ### end Alembic commands ###
