"""CM-791 changing scores PK

Revision ID: c83ff90dbcbf
Revises: 866bfbbdeee0
Create Date: 2021-08-29 17:11:18.313369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql


# revision identifiers, used by Alembic.
revision = "c83ff90dbcbf"
down_revision = "866bfbbdeee0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("pk_scores", "scores", type_="primary")
    op.drop_column("scores", "scores_id")
    op.alter_column(
        "scores",
        column_name="session_uuid",
        new_column_name="quiz_uuid",
        existing_nullable=True,
        nullable=False,
        existing_type=mssql.UNIQUEIDENTIFIER(),
    )
    op.create_primary_key("pk_scores", "scores", ["quiz_uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    print("Too many changes made to work out backward route")
    # who cares ¯\_(ツ)_/¯ ?
    # ### end Alembic commands ###
