"""put foreign key constraints back in for uuid columns

Revision ID: 73360b3341d2
Revises: b53b3fb50a6e
Create Date: 2021-02-28 21:31:09.337399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "73360b3341d2"
down_revision = "b53b3fb50a6e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "climate_feed", "sessions", ["session_uuid"], ["session_uuid"]
    )
    op.drop_column("climate_feed", "session_id")
    op.add_column(
        "scores", sa.Column("user_uuid", mssql.UNIQUEIDENTIFIER(), nullable=True)
    )
    op.create_foreign_key(None, "scores", "users", ["user_uuid"], ["user_uuid"])
    op.create_foreign_key(
        None, "scores", "sessions", ["session_uuid"], ["session_uuid"]
    )
    op.drop_column("scores", "session_id")
    op.drop_column("scores", "user_id")
    op.drop_column("sessions", "session_id")
    op.create_foreign_key(
        None, "signup", "sessions", ["session_uuid"], ["session_uuid"]
    )
    # THERE'S NO session_id
    # op.drop_column("signup", "session_id")
    op.drop_column("users", "user_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "user_id",
            sa.VARCHAR(length=256, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "signup",
        sa.Column(
            "session_id",
            sa.VARCHAR(length=256, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "signup", type_="foreignkey")
    op.add_column(
        "sessions",
        sa.Column(
            "session_id",
            sa.VARCHAR(length=256, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "scores",
        sa.Column(
            "user_id",
            sa.VARCHAR(length=256, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "scores",
        sa.Column(
            "session_id",
            sa.VARCHAR(length=256, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "scores", type_="foreignkey")
    op.drop_constraint(None, "scores", type_="foreignkey")
    op.drop_column("scores", "user_uuid")
    op.add_column(
        "climate_feed",
        sa.Column(
            "session_id",
            sa.VARCHAR(length=256, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "climate_feed", type_="foreignkey")
    # ### end Alembic commands ###
