"""CM1064 - add is_marked_deleted column to conversations tbl

Revision ID: 6bc3b08df49a
Revises: 290fde6228aa
Create Date: 2022-08-06 04:03:27.497463

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "6bc3b08df49a"
down_revision = "290fde6228aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column(
            "is_marked_deleted",
            sa.Boolean(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.alter_column(
        "password_reset_links", "used", existing_type=mssql.BIT(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "password_reset_links", "used", existing_type=mssql.BIT(), nullable=True
    )
    op.drop_column("conversations", "is_marked_deleted")
    # ### end Alembic commands ###
