"""CM-566 conversation used field fixed

Revision ID: 2b11a0ca6ddc
Revises: 6bc3b08df49a
Create Date: 2022-08-21 22:05:03.254767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "2b11a0ca6ddc"
down_revision = "6bc3b08df49a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "password_reset_links", "used", existing_type=mssql.BIT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "password_reset_links", "used", existing_type=mssql.BIT(), nullable=False
    )
    # ### end Alembic commands ###
