"""CM-1045 V2 convo state and user a rating

Revision ID: 3386db04b3ae
Revises: 69f06b708589
Create Date: 2022-05-27 19:43:03.131549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3386db04b3ae"
down_revision = "69f06b708589"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("state", sa.Integer(), nullable=True))
    op.add_column(
        "conversations", sa.Column("user_a_rating", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "user_a_rating")
    op.drop_column("conversations", "state")
    # ### end Alembic commands ###
