"""CM-1064 delete conversation

Revision ID: 36e30a9ce844
Revises: 290fde6228aa
Create Date: 2022-07-31 19:06:27.897162

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "36e30a9ce844"
down_revision = "290fde6228aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column(
            "is_hidden", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
    )
    op.alter_column(
        "password_reset_links", "used", existing_type=mssql.BIT(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "password_reset_links", "used", existing_type=mssql.BIT(), nullable=True
    )
    op.drop_column("conversations", "is_hidden")
    # ### end Alembic commands ###
