"""CM-1067 default conversation state

Revision ID: 290fde6228aa
Revises: f8e607f39eeb
Create Date: 2022-07-09 21:52:59.624995

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "290fde6228aa"
down_revision = "f8e607f39eeb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("update conversations set state = 0 where state is null")
    op.alter_column(
        "conversations", "state", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("conversations", "state", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
