"""#499 user set null on delete

Revision ID: 7d5d345fee36
Revises: aaa676c74969
Create Date: 2023-09-30 23:01:04.348438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "7d5d345fee36"
down_revision = "aaa676c74969"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "conversations",
        "sender_user_uuid",
        existing_type=mssql.UNIQUEIDENTIFIER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "conversations",
        "sender_user_uuid",
        existing_type=mssql.UNIQUEIDENTIFIER(),
        nullable=False,
    )
    # ### end Alembic commands ###
