"""recreating tables with new structure

Revision ID: 6cac2744e717
Revises: 
Create Date: 2020-09-19 12:29:03.388212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cac2744e717'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iri', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iri')
    )
    op.create_table('zip',
    sa.Column('zip', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('zip')
    )
    op.create_table('lrf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_id', sa.Integer(), nullable=True),
    sa.Column('iri_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['iri_id'], ['iri.id'], ),
    sa.ForeignKeyConstraint(['zip_id'], ['zip.zip'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('zip', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zip'], ['zip.zip'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('scores',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('security', sa.Integer(), nullable=True),
    sa.Column('conformity', sa.Integer(), nullable=True),
    sa.Column('benevolence', sa.Integer(), nullable=True),
    sa.Column('tradition', sa.Integer(), nullable=True),
    sa.Column('universalism', sa.Integer(), nullable=True),
    sa.Column('self_direction', sa.Integer(), nullable=True),
    sa.Column('stimulation', sa.Integer(), nullable=True),
    sa.Column('hedonism', sa.Integer(), nullable=True),
    sa.Column('achievement', sa.Integer(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('lrf')
    op.drop_table('zip')
    op.drop_table('iri')
    # ### end Alembic commands ###
