"""CM-246 add zip_code column to sessions model to store user zip code alongside session_id in db

Revision ID: b039ab076716
Revises: 04f4c14bd4af
Create Date: 2020-12-23 21:09:40.551609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b039ab076716"
down_revision = "04f4c14bd4af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sessions", sa.Column("postal_code", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "postal_code")
    # ### end Alembic commands ###
