"""CM-768 FKs for session_uuid in signup and climatefeed

Revision ID: 2a835413c26f
Revises: 5f175a28a8f4
Create Date: 2021-07-15 09:22:35.267364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2a835413c26f"
down_revision = "5f175a28a8f4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None, "climate_feed", "sessions", ["session_uuid"], ["session_uuid"]
    )
    op.create_foreign_key(
        None, "signup", "sessions", ["session_uuid"], ["session_uuid"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "signup", type_="foreignkey")
    op.drop_constraint(None, "climate_feed", type_="foreignkey")
    # ### end Alembic commands ###
