"""CM-768 drop postal code column from sessions and update column names

Revision ID: 3cef9031af99
Revises: d625a669fa7d
Create Date: 2021-07-14 19:55:08.926537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3cef9031af99"
down_revision = "d625a669fa7d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sessions", "postal_code")
    op.alter_column("users", column_name="uuid", new_column_name="user_uuid")
    op.alter_column("users", column_name="email", new_column_name="user_email")
    op.alter_column("signup", column_name="email", new_column_name="signup_email")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions",
        sa.Column(
            "postal_code",
            sa.VARCHAR(length=5, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
