"""CM-768 delete user_uuid from scores and add session_uuid and postal_code to scores

Revision ID: 5f175a28a8f4
Revises: 5045530c3c7e
Create Date: 2021-07-15 08:58:41.156940

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "5f175a28a8f4"
down_revision = "5045530c3c7e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scores", sa.Column("postal_code", sa.String(length=5), nullable=True)
    )
    op.add_column(
        "scores", sa.Column("session_uuid", mssql.UNIQUEIDENTIFIER(), nullable=True)
    )
    op.create_foreign_key(
        None, "scores", "sessions", ["session_uuid"], ["session_uuid"]
    )
    op.drop_column("scores", "user_uuid")
    op.add_column(
        "users", sa.Column("quiz_uuid", mssql.UNIQUEIDENTIFIER(), nullable=True)
    )
    op.create_foreign_key(None, "users", "scores", ["quiz_uuid"], ["quiz_uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "quiz_uuid")
    op.add_column(
        "scores",
        sa.Column(
            "user_uuid", mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "scores", type_="foreignkey")
    op.drop_column("scores", "session_uuid")
    op.drop_column("scores", "postal_code")
    # ### end Alembic commands ###
