"""CM-566 Password reset link table

Revision ID: 6c1ddd941abd
Revises: 006f4dde4f7a
Create Date: 2022-06-14 02:30:12.021083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "6c1ddd941abd"
down_revision = "006f4dde4f7a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_reset_links",
        sa.Column("password_reset_link_uuid", mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column("user_uuid", mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column("session_uuid", mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column(
            "password_reset_link_created_timestamp", sa.DateTime(), nullable=False
        ),
        sa.Column("used", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_uuid"],
            ["sessions.session_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uuid"],
            ["users.user_uuid"],
        ),
        sa.PrimaryKeyConstraint("password_reset_link_uuid"),
    )
    op.create_index(
        op.f("ix_password_reset_links_user_uuid"),
        "password_reset_links",
        ["user_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_password_reset_links_user_uuid"), table_name="password_reset_links"
    )
    op.drop_table("password_reset_links")
    # ### end Alembic commands ###
