"""CM-768 add user_uuid with constraint to sessions, add first_name and last_name to users, add session_created_timestamp to sessions, delete full_name from users

Revision ID: 8ea4c2f2efd8
Revises: 3cef9031af99
Create Date: 2021-07-15 08:05:12.907272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "8ea4c2f2efd8"
down_revision = "3cef9031af99"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sessions", sa.Column("session_created_timestamp", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "sessions", sa.Column("user_uuid", mssql.UNIQUEIDENTIFIER(), nullable=True)
    )
    op.create_foreign_key(None, "sessions", "users", ["user_uuid"], ["user_uuid"])
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=50), nullable=False)
    )
    op.add_column("users", sa.Column("last_name", sa.String(length=50), nullable=False))
    op.create_index(op.f("ix_users_user_email"), "users", ["user_email"], unique=True)
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "full_name",
            sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_index(op.f("ix_users_user_email"), table_name="users")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_constraint(None, "sessions", type_="foreignkey")
    op.drop_column("sessions", "user_uuid")
    op.drop_column("sessions", "session_created_timestamp")
    # ### end Alembic commands ###
