"""CM-768 drop scores_id, rename session_uuid in scores to quiz_uuid, make quiz_uuid pk

Revision ID: 5045530c3c7e
Revises: 8ea4c2f2efd8
Create Date: 2021-07-15 08:17:09.726124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql


# revision identifiers, used by Alembic.
revision = "5045530c3c7e"
down_revision = "8ea4c2f2efd8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE scores DROP CONSTRAINT PK__scores__7697EDA280A02E91")
    op.drop_column("scores", "scores_id")
    op.alter_column(
        "scores",
        column_name="session_uuid",
        new_column_name="quiz_uuid",
        existing_nullable=True,
        nullable=False,
        existing_type=mssql.UNIQUEIDENTIFIER(),
    )
    op.create_primary_key("pk_scores", "scores", ["quiz_uuid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scores",
        sa.Column(
            "scores_id",
            sa.INTEGER(),
            autoincrement=True,
            nullable=False,
            mssql_identity_start=1,
            mssql_identity_increment=1,
        ),
    )
    # ### end Alembic commands ###
