"""CM-784 small edits to conversations table

Revision ID: 8bc0ea314d0a
Revises: fff123f40733
Create Date: 2021-09-25 12:46:36.455888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "8bc0ea314d0a"
down_revision = "fff123f40733"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversations",
        sa.Column("conversation_uuid", mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column("sender_user_uuid", mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column("sender_session_uuid", mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column("receiver_session_uuid", mssql.UNIQUEIDENTIFIER(), nullable=True),
        sa.Column("receiver_name", sa.String(length=50), nullable=False),
        sa.Column("conversation_status", sa.Integer(), nullable=True),
        sa.Column("conversation_created_timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["receiver_session_uuid"],
            ["sessions.session_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_session_uuid"],
            ["sessions.session_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_user_uuid"],
            ["users.user_uuid"],
        ),
        sa.PrimaryKeyConstraint("conversation_uuid"),
    )
    op.create_index(
        op.f("ix_conversations_sender_user_uuid"),
        "conversations",
        ["sender_user_uuid"],
        unique=False,
    )
    op.drop_index("ix_conversation_sender_user_uuid", table_name="conversation")
    op.drop_table("conversation")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation",
        sa.Column(
            "conversation_uuid",
            mssql.UNIQUEIDENTIFIER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "sender_user_uuid",
            mssql.UNIQUEIDENTIFIER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "sender_session_uuid",
            mssql.UNIQUEIDENTIFIER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "receiver_session_uuid",
            mssql.UNIQUEIDENTIFIER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "receiver_name",
            sa.VARCHAR(length=50, collation="SQL_Latin1_General_CP1_CI_AS"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "conversation_status", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "conversation_create_time",
            sa.DATETIME(),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["receiver_session_uuid"],
            ["sessions.session_uuid"],
            name="FK__conversat__recei__55009F39",
        ),
        sa.ForeignKeyConstraint(
            ["sender_session_uuid"],
            ["sessions.session_uuid"],
            name="FK__conversat__sende__55F4C372",
        ),
        sa.ForeignKeyConstraint(
            ["sender_user_uuid"],
            ["users.user_uuid"],
            name="FK__conversat__sende__56E8E7AB",
        ),
        sa.PrimaryKeyConstraint(
            "conversation_uuid", name="PK__conversa__77D82F36D5CEBD17"
        ),
    )
    op.create_index(
        "ix_conversation_sender_user_uuid",
        "conversation",
        ["sender_user_uuid"],
        unique=False,
    )
    op.drop_index(op.f("ix_conversations_sender_user_uuid"), table_name="conversations")
    op.drop_table("conversations")
    # ### end Alembic commands ###
