"""CM-784 creating conversations table

Revision ID: fff123f40733
Revises: 2a835413c26f
Create Date: 2021-08-08 00:29:37.281894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = "fff123f40733"
down_revision = "2a835413c26f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation",
        sa.Column("conversation_uuid", mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column("sender_user_uuid", mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column("sender_session_uuid", mssql.UNIQUEIDENTIFIER(), nullable=False),
        sa.Column("receiver_session_uuid", mssql.UNIQUEIDENTIFIER(), nullable=True),
        sa.Column("receiver_name", sa.String(length=50), nullable=False),
        sa.Column("conversation_status", sa.Integer(), nullable=True),
        sa.Column("conversation_create_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["receiver_session_uuid"],
            ["sessions.session_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_session_uuid"],
            ["sessions.session_uuid"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_user_uuid"],
            ["users.user_uuid"],
        ),
        sa.PrimaryKeyConstraint("conversation_uuid"),
    )
    op.create_index(
        op.f("ix_conversation_sender_user_uuid"),
        "conversation",
        ["sender_user_uuid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversation_sender_user_uuid"), table_name="conversation")
    op.drop_table("conversation")
    # ### end Alembic commands ###
